# Generated by Django 3.0 on 2020-01-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('lecture', models.ForeignKey('meetings.lecture', models.SET_NULL, null=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
