# Generated by Django 3.0 on 2020-01-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('homework', '0001_initial'),
    ]

    operations = [
    ]
