# Generated by Django 3.0 on 2020-01-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='update',
            table=None,
        ),
    ]
