/*
 * BRC API
 * This is an API that allows access to Boealps BRC course and participant data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jeanruggiero@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Gear', 'model/GradClimbReview', 'model/Homework', 'model/InstructorReview', 'model/LeavenworthReview', 'model/Lecture', 'model/Outing', 'model/SkillsNightReview', 'model/Squamish1Review', 'model/Squamish2Review', 'model/Student', 'model/Update', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Gear'), require('./model/GradClimbReview'), require('./model/Homework'), require('./model/InstructorReview'), require('./model/LeavenworthReview'), require('./model/Lecture'), require('./model/Outing'), require('./model/SkillsNightReview'), require('./model/Squamish1Review'), require('./model/Squamish2Review'), require('./model/Student'), require('./model/Update'), require('./api/DefaultApi'));
  }
}(function(ApiClient, Gear, GradClimbReview, Homework, InstructorReview, LeavenworthReview, Lecture, Outing, SkillsNightReview, Squamish1Review, Squamish2Review, Student, Update, DefaultApi) {
  'use strict';

  /**
   * This_is_an_API_that_allows_access_to_Boealps_BRC_course_and_participant_data_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var BrcApi = require('index'); // See note below*.
   * var xxxSvc = new BrcApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new BrcApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new BrcApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new BrcApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Gear model constructor.
     * @property {module:model/Gear}
     */
    Gear: Gear,
    /**
     * The GradClimbReview model constructor.
     * @property {module:model/GradClimbReview}
     */
    GradClimbReview: GradClimbReview,
    /**
     * The Homework model constructor.
     * @property {module:model/Homework}
     */
    Homework: Homework,
    /**
     * The InstructorReview model constructor.
     * @property {module:model/InstructorReview}
     */
    InstructorReview: InstructorReview,
    /**
     * The LeavenworthReview model constructor.
     * @property {module:model/LeavenworthReview}
     */
    LeavenworthReview: LeavenworthReview,
    /**
     * The Lecture model constructor.
     * @property {module:model/Lecture}
     */
    Lecture: Lecture,
    /**
     * The Outing model constructor.
     * @property {module:model/Outing}
     */
    Outing: Outing,
    /**
     * The SkillsNightReview model constructor.
     * @property {module:model/SkillsNightReview}
     */
    SkillsNightReview: SkillsNightReview,
    /**
     * The Squamish1Review model constructor.
     * @property {module:model/Squamish1Review}
     */
    Squamish1Review: Squamish1Review,
    /**
     * The Squamish2Review model constructor.
     * @property {module:model/Squamish2Review}
     */
    Squamish2Review: Squamish2Review,
    /**
     * The Student model constructor.
     * @property {module:model/Student}
     */
    Student: Student,
    /**
     * The Update model constructor.
     * @property {module:model/Update}
     */
    Update: Update,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
