/*
 * BRC API
 * This is an API that allows access to Boealps BRC course and participant data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jeanruggiero@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Outing'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Outing'));
  } else {
    // Browser globals (root is window)
    if (!root.BrcApi) {
      root.BrcApi = {};
    }
    root.BrcApi.InstructorReview = factory(root.BrcApi.ApiClient, root.BrcApi.Outing);
  }
}(this, function(ApiClient, Outing) {
  'use strict';

  /**
   * The InstructorReview model module.
   * @module model/InstructorReview
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InstructorReview</code>.
   * @alias module:model/InstructorReview
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InstructorReview</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InstructorReview} obj Optional instance to populate.
   * @return {module:model/InstructorReview} The populated <code>InstructorReview</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('instructor'))
        obj.instructor = ApiClient.convertToType(data['instructor'], Object);
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], Object);
      if (data.hasOwnProperty('outing'))
        obj.outing = Outing.constructFromObject(data['outing']);
      if (data.hasOwnProperty('learning_style'))
        obj.learningStyle = ApiClient.convertToType(data['learning_style'], 'Number');
      if (data.hasOwnProperty('explanations'))
        obj.explanations = ApiClient.convertToType(data['explanations'], 'Number');
      if (data.hasOwnProperty('demos'))
        obj.demos = ApiClient.convertToType(data['demos'], 'Number');
      if (data.hasOwnProperty('patience'))
        obj.patience = ApiClient.convertToType(data['patience'], 'Number');
      if (data.hasOwnProperty('did_well'))
        obj.didWell = ApiClient.convertToType(data['did_well'], 'String');
      if (data.hasOwnProperty('did_bad'))
        obj.didBad = ApiClient.convertToType(data['did_bad'], 'String');
      if (data.hasOwnProperty('safety'))
        obj.safety = ApiClient.convertToType(data['safety'], 'String');
      if (data.hasOwnProperty('comments'))
        obj.comments = ApiClient.convertToType(data['comments'], 'String');
    }
    return obj;
  }

  /**
   * a Django User object
   * @member {Object} instructor
   */
  exports.prototype.instructor = undefined;

  /**
   * authenticated Django User
   * @member {Object} author
   */
  exports.prototype.author = undefined;

  /**
   * @member {module:model/Outing} outing
   */
  exports.prototype.outing = undefined;

  /**
   * @member {Number} learningStyle
   */
  exports.prototype.learningStyle = undefined;

  /**
   * @member {Number} explanations
   */
  exports.prototype.explanations = undefined;

  /**
   * @member {Number} demos
   */
  exports.prototype.demos = undefined;

  /**
   * @member {Number} patience
   */
  exports.prototype.patience = undefined;

  /**
   * @member {String} didWell
   */
  exports.prototype.didWell = undefined;

  /**
   * @member {String} didBad
   */
  exports.prototype.didBad = undefined;

  /**
   * @member {String} safety
   */
  exports.prototype.safety = undefined;

  /**
   * @member {String} comments
   */
  exports.prototype.comments = undefined;

  return exports;

}));
