/*
 * BRC API
 * This is an API that allows access to Boealps BRC course and participant data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jeanruggiero@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Outing', 'model/Student'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Outing'), require('./Student'));
  } else {
    // Browser globals (root is window)
    if (!root.BrcApi) {
      root.BrcApi = {};
    }
    root.BrcApi.LeavenworthReview = factory(root.BrcApi.ApiClient, root.BrcApi.Outing, root.BrcApi.Student);
  }
}(this, function(ApiClient, Outing, Student) {
  'use strict';

  /**
   * The LeavenworthReview model module.
   * @module model/LeavenworthReview
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LeavenworthReview</code>.
   * @alias module:model/LeavenworthReview
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>LeavenworthReview</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LeavenworthReview} obj Optional instance to populate.
   * @return {module:model/LeavenworthReview} The populated <code>LeavenworthReview</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('student'))
        obj.student = Student.constructFromObject(data['student']);
      if (data.hasOwnProperty('instructor'))
        obj.instructor = ApiClient.convertToType(data['instructor'], Object);
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
      if (data.hasOwnProperty('outing'))
        obj.outing = Outing.constructFromObject(data['outing']);
      if (data.hasOwnProperty('knots'))
        obj.knots = ApiClient.convertToType(data['knots'], 'Number');
      if (data.hasOwnProperty('belay'))
        obj.belay = ApiClient.convertToType(data['belay'], 'Number');
      if (data.hasOwnProperty('rappel'))
        obj.rappel = ApiClient.convertToType(data['rappel'], 'Number');
      if (data.hasOwnProperty('systems'))
        obj.systems = ApiClient.convertToType(data['systems'], 'Number');
      if (data.hasOwnProperty('anchor_safety'))
        obj.anchorSafety = ApiClient.convertToType(data['anchor_safety'], 'Number');
      if (data.hasOwnProperty('gear_placement'))
        obj.gearPlacement = ApiClient.convertToType(data['gear_placement'], 'Number');
      if (data.hasOwnProperty('anchor_building'))
        obj.anchorBuilding = ApiClient.convertToType(data['anchor_building'], 'Number');
      if (data.hasOwnProperty('safety'))
        obj.safety = ApiClient.convertToType(data['safety'], 'Number');
      if (data.hasOwnProperty('efficiency'))
        obj.efficiency = ApiClient.convertToType(data['efficiency'], 'Number');
      if (data.hasOwnProperty('gear_cleaning'))
        obj.gearCleaning = ApiClient.convertToType(data['gear_cleaning'], 'Number');
      if (data.hasOwnProperty('technique'))
        obj.technique = ApiClient.convertToType(data['technique'], 'Number');
      if (data.hasOwnProperty('routefinding'))
        obj.routefinding = ApiClient.convertToType(data['routefinding'], 'Number');
      if (data.hasOwnProperty('areas'))
        obj.areas = ApiClient.convertToType(data['areas'], 'String');
      if (data.hasOwnProperty('current_comfort_grade'))
        obj.currentComfortGrade = ApiClient.convertToType(data['current_comfort_grade'], 'String');
      if (data.hasOwnProperty('current_limit_grade'))
        obj.currentLimitGrade = ApiClient.convertToType(data['current_limit_grade'], 'String');
      if (data.hasOwnProperty('recommendation'))
        obj.recommendation = ApiClient.convertToType(data['recommendation'], 'String');
      if (data.hasOwnProperty('comments'))
        obj.comments = ApiClient.convertToType(data['comments'], 'String');
      if (data.hasOwnProperty('leavenworth_clean_and_rappel_bolts'))
        obj.leavenworthCleanAndRappelBolts = ApiClient.convertToType(data['leavenworth_clean_and_rappel_bolts'], 'Number');
      if (data.hasOwnProperty('guide_mode'))
        obj.guideMode = ApiClient.convertToType(data['guide_mode'], 'Number');
    }
    return obj;
  }

  /**
   * @member {module:model/Student} student
   */
  exports.prototype.student = undefined;

  /**
   * authenticated User object
   * @member {Object} instructor
   */
  exports.prototype.instructor = undefined;

  /**
   * @member {String} time
   */
  exports.prototype.time = undefined;

  /**
   * @member {module:model/Outing} outing
   */
  exports.prototype.outing = undefined;

  /**
   * @member {Number} knots
   */
  exports.prototype.knots = undefined;

  /**
   * @member {Number} belay
   */
  exports.prototype.belay = undefined;

  /**
   * @member {Number} rappel
   */
  exports.prototype.rappel = undefined;

  /**
   * @member {Number} systems
   */
  exports.prototype.systems = undefined;

  /**
   * @member {Number} anchorSafety
   */
  exports.prototype.anchorSafety = undefined;

  /**
   * @member {Number} gearPlacement
   */
  exports.prototype.gearPlacement = undefined;

  /**
   * @member {Number} anchorBuilding
   */
  exports.prototype.anchorBuilding = undefined;

  /**
   * @member {Number} safety
   */
  exports.prototype.safety = undefined;

  /**
   * @member {Number} efficiency
   */
  exports.prototype.efficiency = undefined;

  /**
   * @member {Number} gearCleaning
   */
  exports.prototype.gearCleaning = undefined;

  /**
   * @member {Number} technique
   */
  exports.prototype.technique = undefined;

  /**
   * @member {Number} routefinding
   */
  exports.prototype.routefinding = undefined;

  /**
   * @member {String} areas
   */
  exports.prototype.areas = undefined;

  /**
   * @member {String} currentComfortGrade
   */
  exports.prototype.currentComfortGrade = undefined;

  /**
   * @member {String} currentLimitGrade
   */
  exports.prototype.currentLimitGrade = undefined;

  /**
   * @member {String} recommendation
   */
  exports.prototype.recommendation = undefined;

  /**
   * @member {String} comments
   */
  exports.prototype.comments = undefined;

  /**
   * @member {Number} leavenworthCleanAndRappelBolts
   */
  exports.prototype.leavenworthCleanAndRappelBolts = undefined;

  /**
   * @member {Number} guideMode
   */
  exports.prototype.guideMode = undefined;

  return exports;

}));
