/*
 * BRC API
 * This is an API that allows access to Boealps BRC course and participant data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jeanruggiero@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BrcApi) {
      root.BrcApi = {};
    }
    root.BrcApi.Lecture = factory(root.BrcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Lecture model module.
   * @module model/Lecture
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Lecture</code>.
   * @alias module:model/Lecture
   * @class
   * @param _number {Number} 
   * @param topic {String} 
   * @param time {String} 
   * @param location {String} 
   */
  var exports = function(_number, topic, time, location) {
    this._number = _number;
    this.topic = topic;
    this.time = time;
    this.location = location;
  };

  /**
   * Constructs a <code>Lecture</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Lecture} obj Optional instance to populate.
   * @return {module:model/Lecture} The populated <code>Lecture</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'Number');
      if (data.hasOwnProperty('topic'))
        obj.topic = ApiClient.convertToType(data['topic'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('presentationFile'))
        obj.presentationFile = ApiClient.convertToType(data['presentationFile'], 'String');
      if (data.hasOwnProperty('locationLink'))
        obj.locationLink = ApiClient.convertToType(data['locationLink'], 'String');
      if (data.hasOwnProperty('potluckLink'))
        obj.potluckLink = ApiClient.convertToType(data['potluckLink'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} _number
   */
  exports.prototype._number = undefined;

  /**
   * @member {String} topic
   */
  exports.prototype.topic = undefined;

  /**
   * @member {String} time
   */
  exports.prototype.time = undefined;

  /**
   * @member {String} location
   */
  exports.prototype.location = undefined;

  /**
   * @member {String} presentationFile
   */
  exports.prototype.presentationFile = undefined;

  /**
   * @member {String} locationLink
   */
  exports.prototype.locationLink = undefined;

  /**
   * @member {String} potluckLink
   */
  exports.prototype.potluckLink = undefined;

  return exports;

}));
