/*
 * BRC API
 * This is an API that allows access to Boealps BRC course and participant data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jeanruggiero@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Outing', 'model/Student'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Outing'), require('./Student'));
  } else {
    // Browser globals (root is window)
    if (!root.BrcApi) {
      root.BrcApi = {};
    }
    root.BrcApi.SkillsNightReview = factory(root.BrcApi.ApiClient, root.BrcApi.Outing, root.BrcApi.Student);
  }
}(this, function(ApiClient, Outing, Student) {
  'use strict';

  /**
   * The SkillsNightReview model module.
   * @module model/SkillsNightReview
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SkillsNightReview</code>.
   * @alias module:model/SkillsNightReview
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SkillsNightReview</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SkillsNightReview} obj Optional instance to populate.
   * @return {module:model/SkillsNightReview} The populated <code>SkillsNightReview</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('student'))
        obj.student = Student.constructFromObject(data['student']);
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
      if (data.hasOwnProperty('outing'))
        obj.outing = Outing.constructFromObject(data['outing']);
      if (data.hasOwnProperty('rewoven_figure_8'))
        obj.rewovenFigure8 = ApiClient.convertToType(data['rewoven_figure_8'], 'Number');
      if (data.hasOwnProperty('figure_8_bight'))
        obj.figure8Bight = ApiClient.convertToType(data['figure_8_bight'], 'Number');
      if (data.hasOwnProperty('prusik'))
        obj.prusik = ApiClient.convertToType(data['prusik'], 'Number');
      if (data.hasOwnProperty('bachmann'))
        obj.bachmann = ApiClient.convertToType(data['bachmann'], 'Number');
      if (data.hasOwnProperty('double_fisherman'))
        obj.doubleFisherman = ApiClient.convertToType(data['double_fisherman'], 'Number');
      if (data.hasOwnProperty('water_knot'))
        obj.waterKnot = ApiClient.convertToType(data['water_knot'], 'Number');
      if (data.hasOwnProperty('clove_hitch'))
        obj.cloveHitch = ApiClient.convertToType(data['clove_hitch'], 'Number');
      if (data.hasOwnProperty('munter_hitch'))
        obj.munterHitch = ApiClient.convertToType(data['munter_hitch'], 'Number');
      if (data.hasOwnProperty('butterfly'))
        obj.butterfly = ApiClient.convertToType(data['butterfly'], 'Number');
      if (data.hasOwnProperty('euro_death_knot'))
        obj.euroDeathKnot = ApiClient.convertToType(data['euro_death_knot'], 'Number');
      if (data.hasOwnProperty('rope_coiling'))
        obj.ropeCoiling = ApiClient.convertToType(data['rope_coiling'], 'Number');
      if (data.hasOwnProperty('lead_belay'))
        obj.leadBelay = ApiClient.convertToType(data['lead_belay'], 'Number');
      if (data.hasOwnProperty('lead_fall'))
        obj.leadFall = ApiClient.convertToType(data['lead_fall'], 'Number');
      if (data.hasOwnProperty('escape_belay'))
        obj.escapeBelay = ApiClient.convertToType(data['escape_belay'], 'Number');
      if (data.hasOwnProperty('mechanical_autoblock'))
        obj.mechanicalAutoblock = ApiClient.convertToType(data['mechanical_autoblock'], 'Number');
      if (data.hasOwnProperty('munter_rappel'))
        obj.munterRappel = ApiClient.convertToType(data['munter_rappel'], 'Number');
      if (data.hasOwnProperty('clean_rappel_bolts'))
        obj.cleanRappelBolts = ApiClient.convertToType(data['clean_rappel_bolts'], 'Number');
      if (data.hasOwnProperty('setting_bolted_anchor'))
        obj.settingBoltedAnchor = ApiClient.convertToType(data['setting_bolted_anchor'], 'Number');
      if (data.hasOwnProperty('ascending_rope'))
        obj.ascendingRope = ApiClient.convertToType(data['ascending_rope'], 'Number');
      if (data.hasOwnProperty('comments'))
        obj.comments = ApiClient.convertToType(data['comments'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/Student} student
   */
  exports.prototype.student = undefined;

  /**
   * @member {String} time
   */
  exports.prototype.time = undefined;

  /**
   * @member {module:model/Outing} outing
   */
  exports.prototype.outing = undefined;

  /**
   * @member {Number} rewovenFigure8
   */
  exports.prototype.rewovenFigure8 = undefined;

  /**
   * @member {Number} figure8Bight
   */
  exports.prototype.figure8Bight = undefined;

  /**
   * @member {Number} prusik
   */
  exports.prototype.prusik = undefined;

  /**
   * @member {Number} bachmann
   */
  exports.prototype.bachmann = undefined;

  /**
   * @member {Number} doubleFisherman
   */
  exports.prototype.doubleFisherman = undefined;

  /**
   * @member {Number} waterKnot
   */
  exports.prototype.waterKnot = undefined;

  /**
   * @member {Number} cloveHitch
   */
  exports.prototype.cloveHitch = undefined;

  /**
   * @member {Number} munterHitch
   */
  exports.prototype.munterHitch = undefined;

  /**
   * @member {Number} butterfly
   */
  exports.prototype.butterfly = undefined;

  /**
   * @member {Number} euroDeathKnot
   */
  exports.prototype.euroDeathKnot = undefined;

  /**
   * @member {Number} ropeCoiling
   */
  exports.prototype.ropeCoiling = undefined;

  /**
   * @member {Number} leadBelay
   */
  exports.prototype.leadBelay = undefined;

  /**
   * @member {Number} leadFall
   */
  exports.prototype.leadFall = undefined;

  /**
   * @member {Number} escapeBelay
   */
  exports.prototype.escapeBelay = undefined;

  /**
   * @member {Number} mechanicalAutoblock
   */
  exports.prototype.mechanicalAutoblock = undefined;

  /**
   * @member {Number} munterRappel
   */
  exports.prototype.munterRappel = undefined;

  /**
   * @member {Number} cleanRappelBolts
   */
  exports.prototype.cleanRappelBolts = undefined;

  /**
   * @member {Number} settingBoltedAnchor
   */
  exports.prototype.settingBoltedAnchor = undefined;

  /**
   * @member {Number} ascendingRope
   */
  exports.prototype.ascendingRope = undefined;

  /**
   * @member {String} comments
   */
  exports.prototype.comments = undefined;

  return exports;

}));
