/*
 * BRC API
 * This is an API that allows access to Boealps BRC course and participant data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jeanruggiero@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BrcApi) {
      root.BrcApi = {};
    }
    root.BrcApi.Update = factory(root.BrcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Update model module.
   * @module model/Update
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Update</code>.
   * @alias module:model/Update
   * @class
   * @param id {Number} 
   * @param time {String} 
   * @param title {String} 
   * @param content {String} 
   */
  var exports = function(id, time, title, content) {
    this.id = id;
    this.time = time;
    this.title = title;
    this.content = content;
  };

  /**
   * Constructs a <code>Update</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Update} obj Optional instance to populate.
   * @return {module:model/Update} The populated <code>Update</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], 'Number');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * primary key value for a User object
   * @member {Number} author
   */
  exports.prototype.author = undefined;

  /**
   * @member {String} time
   */
  exports.prototype.time = undefined;

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {String} content
   */
  exports.prototype.content = undefined;

  return exports;

}));
