# Generated by Django 3.0 on 2020-01-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=128, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.ImageField(null=True, upload_to='profile_photos/')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('favorite_climb', models.TextField(blank=True, null=True)),
                ('goal_climb', models.TextField(blank=True, null=True)),
                ('fun_fact', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('zip', models.CharField(max_length=128)),
                ('insurance_carrier', models.CharField(max_length=128)),
                ('emergency_contact', models.CharField(max_length=128)),
                ('emergency_contact_phone', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
