# Generated by Django 3.0 on 2020-01-25 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0002_remove_outing_gear_list'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('knots', models.IntegerField(blank=True, null=True)),
                ('belay', models.IntegerField(blank=True, null=True)),
                ('rappel', models.IntegerField(blank=True, null=True)),
                ('systems', models.IntegerField(blank=True, null=True)),
                ('anchor_safety', models.IntegerField(blank=True, null=True)),
                ('gear_placement', models.IntegerField(blank=True, null=True)),
                ('anchor_building', models.IntegerField(blank=True, null=True)),
                ('safety', models.IntegerField(blank=True, null=True)),
                ('efficiency', models.IntegerField(blank=True, null=True)),
                ('gear_cleaning', models.IntegerField(blank=True, null=True)),
                ('technique', models.IntegerField(blank=True, null=True)),
                ('routefinding', models.IntegerField(blank=True, null=True)),
                ('areas', models.TextField()),
                ('current_comfort_grade', models.CharField(max_length=128)),
                ('current_limit_grade', models.CharField(max_length=128)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Outing')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='GradClimbReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.Review')),
                ('trip_planning', models.IntegerField(blank=True, null=True)),
                ('beta_sheet', models.IntegerField(blank=True, null=True)),
                ('transitions', models.IntegerField(blank=True, null=True)),
                ('communication', models.IntegerField(blank=True, null=True)),
            ],
            bases=('reviews.review',),
        ),
        migrations.CreateModel(
            name='LeavenworthReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.Review')),
                ('leavenworth_clean_and_rappel_bolts', models.IntegerField(blank=True, null=True)),
                ('guide_mode', models.IntegerField(blank=True, null=True)),
            ],
            bases=('reviews.review',),
        ),
        migrations.CreateModel(
            name='Squamish1Review',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.Review')),
                ('clean_and_rappel', models.IntegerField(blank=True, null=True)),
            ],
            bases=('reviews.review',),
        ),
        migrations.CreateModel(
            name='Squamish2Review',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.Review')),
                ('squamish2_transitions', models.IntegerField(blank=True, null=True)),
                ('squamish2_communication', models.IntegerField(blank=True, null=True)),
            ],
            bases=('reviews.review',),
        ),
        migrations.CreateModel(
            name='SkillsNightReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('rewoven_figure_8', models.IntegerField(blank=True, null=True)),
                ('figure_8_bight', models.IntegerField(blank=True, null=True)),
                ('prusik', models.IntegerField(blank=True, null=True)),
                ('bachmann', models.IntegerField(blank=True, null=True)),
                ('double_fisherman', models.IntegerField(blank=True, null=True)),
                ('water_knot', models.IntegerField(blank=True, null=True)),
                ('clove_hitch', models.IntegerField(blank=True, null=True)),
                ('munter_hitch', models.IntegerField(blank=True, null=True)),
                ('butterfly', models.IntegerField(blank=True, null=True)),
                ('euro_death_knot', models.IntegerField(blank=True, null=True)),
                ('rope_coiling', models.IntegerField(blank=True, null=True)),
                ('lead_belay', models.IntegerField(blank=True, null=True)),
                ('lead_fall', models.IntegerField(blank=True, null=True)),
                ('escape_belay', models.IntegerField(blank=True, null=True)),
                ('mechanical_autoblock', models.IntegerField(blank=True, null=True)),
                ('munter_rappel', models.IntegerField(blank=True, null=True)),
                ('clean_rappel_bolts', models.IntegerField(blank=True, null=True)),
                ('setting_bolted_anchor', models.IntegerField(blank=True, null=True)),
                ('ascending_rope', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('outing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Outing')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.IntegerField(blank=True, null=True)),
                ('explanations', models.IntegerField(blank=True, null=True)),
                ('demos', models.IntegerField(blank=True, null=True)),
                ('patience', models.IntegerField(blank=True, null=True)),
                ('did_well', models.TextField(blank=True, null=True)),
                ('did_bad', models.TextField(blank=True, null=True)),
                ('safety', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_authored', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.Outing')),
            ],
        ),
    ]
