# Generated by Django 3.0 on 2020-01-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GearTwo',
            new_name='Gear',
        ),
        migrations.AlterModelTable(
            name='gear',
            table='profiles_gear',
        ),
    ]
