# Generated by Django 3.0 on 2020-01-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_auto_20200125_0059'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gear',
            table='profiles_gear',
        ),
    ]
