# Generated by Django 3.0 on 2020-01-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_auto_20200125_0100'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gear',
            table='profiles_gear',
        ),
    ]
