# Generated by Django 3.0 on 2020-01-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0006_auto_20200125_0103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gear',
            table=None,
        ),
    ]
