# Generated by Django 3.0.2 on 2020-01-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0007_auto_20200125_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='recommendation',
            new_name='recommendation_url',
        ),
    ]
