# Generated by Django 3.0 on 2020-01-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gear', '0007_auto_20200125_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=250)),
                ('presentation_file', models.URLField(blank=True, null=True)),
                ('location_link', models.URLField(blank=True, null=True)),
                ('potluck_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profiles_lecture',
            },
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('objectives', models.TextField()),
                ('description', models.TextField()),
                ('itinerary', models.TextField()),
                ('campground', models.CharField(blank=True, max_length=300, null=True)),
                ('campsite', models.CharField(blank=True, max_length=300, null=True)),
                ('camping_location', models.URLField(blank=True, null=True)),
                ('camping_checkin', models.DateTimeField(blank=True, null=True)),
                ('gear_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gear.Gear')),
            ],
            options={
                'db_table': 'profiles_outing',
            },
        ),
    ]
