# Generated by Django 3.0 on 2020-01-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_outing_gear_list'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lecture',
            table=None,
        ),
        migrations.AlterModelTable(
            name='outing',
            table=None,
        ),
    ]
