# Generated by Django 3.0.2 on 2020-01-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20200125_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outing',
            old_name='camping_checkin',
            new_name='camping_checkin_time',
        ),
        migrations.RenameField(
            model_name='outing',
            old_name='camping_location',
            new_name='camping_location_url',
        ),
    ]
