# Generated by Django 3.0.2 on 2020-01-26 21:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20200126_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='objectives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
